server:
  port: 8080

spring:
  datasource:
    # for root pwd is rootroot
    username: lottery
    password: lottery
    url: jdbc:mysql://localhost:3306/lottery?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    schemas: lottery
    enabled: true
    locations: classpath:db/migration # SQL 脚本存放路径
    baseline-on-migrate: true # 如果数据库中已有表，设置基线
    clean-disabled: true # 禁止清空数据库

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# Dubbo 广播方式配置
dubbo:
  application:
    name: Lottery
    version: 1.0.0
  registry:
    address: N/A #multicast://224.5.6.7:1234
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: cn.itedus.lottery.rpc
logging:
  level:
    root: INFO
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.flywaydb: DEBUG